version: 2

sources:
  - name: raw
    description: "Raw telecom events landing (hourly rows)."
    tables:
      - name: tower_events
        description: "Uploaded CSV ingested to warehouse as raw.tower_events."
        columns:
          - name: timestamp
            tests: [not_null]
          - name: tower_id
            tests: [not_null]
          - name: users_connected
          - name: download_speed
          - name: upload_speed
          - name: latency
          - name: weather
          - name: congestion

models:
  - name: stg_tower_events
    description: "Typed, cleaned raw events."
    columns:
      - name: event_ts
        tests: [not_null]
      - name: tower_id
        tests: [not_null]
      - name: users_connected
      - name: download_speed_mbps
      - name: upload_speed_mbps
      - name: latency_ms
      - name: weather
      - name: congestion_flag
